apiVersion: v1

kind: Service
metadata:
  labels:
    app: mongo
  name: mongo
  namespace: webdev-nav
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
    app: mongo
    