apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mongo-claim0
  name: mongo-claim0
  namespace: webdev-nav
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi