apiVersion: v1
kind: PersistentVolumeClaim
metadata:
     
  name: mongo-claim0
  namespace: webdev-nav
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  
  resources:
    requests:
      storage: 1Gi