kind: PersistentVolume
apiVersion: v1
metadata:
 name: mongo-pv
 namespace: webdev-nav
 labels:
  type: local
spec:
 storageClassName: manual
 capacity:
  storage: 1Gi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: "/mnt/mongo_data"
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   namespace: webdev-nav
#   name: mongo-pv
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#       path: "./mongo-data"