apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: webdev-nav
  name: nginx
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mongo
  targetCPUUtilizationPercentage: 35