apiVersion: apps/v1

kind: Deployment

metadata:
  name: frontend-pod
  namespace: webdev-nav
  labels:
    app: frontend-pod

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-pod

  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend-pod

    spec:
      containers:
      
        - name: frontend-container
          image: neosoporte/frontendvm
          imagePullPolicy: Always
          ports:
            - containerPort: 80 