kind: Namespace
apiVersion: v1
metadata:
  name: webdev-nav
 
  
  labels:
    kubernetes.io/metadata.name: webdev-nav
    name: webdev-nav
  managedFields:
    - manager: dashboard
      operation: Update
      apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:kubernetes.io/metadata.name': {}
            'f:name': {}
